# Generated by Django 3.2.17 on 2023-02-21 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capt', models.CharField(max_length=255)),
                ('app_url', models.CharField(max_length=255)),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.mainmenu')),
            ],
        ),
    ]
