# Generated by Django 3.2.17 on 2023-02-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230221_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Иконка'),
        ),
    ]
