# Generated by Django 3.2.17 on 2023-02-21 08:09

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mainmenu_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='main.mainmenu', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mainmenu',
            unique_together={('parent',)},
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='root',
        ),
    ]
