# Generated by Django 3.2.17 on 2023-02-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230222_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='asdf',
            field=models.IntegerField(null=True),
        ),
    ]
