# Generated by Django 3.2.17 on 2023-02-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_mainmenu_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainmenu',
            name='asdf',
        ),
    ]
