# Generated by Django 3.2.17 on 2023-02-22 02:56

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230222_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='main.mainmenu', verbose_name='Родитель'),
        ),
    ]
