# Generated by Django 3.2.17 on 2023-02-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20230222_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mainmenu',
            unique_together={('parent', 'slug')},
        ),
    ]
