# Generated by Django 3.2.17 on 2023-02-27 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20230222_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.mainmenu', verbose_name='Родитель'),
        ),
        migrations.AlterUniqueTogether(
            name='mainmenu',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='level',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='tree_id',
        ),
    ]
