# Generated by Django 3.2.17 on 2023-02-27 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20230227_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='main.mainmenu', verbose_name='Родитель'),
        ),
    ]
