# Generated by Django 3.2.17 on 2023-02-27 05:32

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20230227_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='main.mainmenu', verbose_name='Родитель'),
        ),
    ]
