# Generated by Django 4.2.1 on 2024-03-13 03:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0018_alter_mainmenu_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='groups', to='auth.group', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
