# Generated by Django 3.2.17 on 2023-02-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecp',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ecp',
            name='key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
