# Generated by Django 3.2.17 on 2023-02-07 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0002_auto_20230207_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='persons',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecp.departments'),
        ),
    ]
