# Generated by Django 3.2.17 on 2023-02-07 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0003_auto_20230207_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecp',
            old_name='fk_person',
            new_name='fk_person_id',
        ),
        migrations.RenameField(
            model_name='persons',
            old_name='dep',
            new_name='fk_department_id',
        ),
    ]
