# Generated by Django 3.2.17 on 2023-02-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0004_auto_20230207_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecp',
            old_name='fk_person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='persons',
            old_name='fk_department_id',
            new_name='dep',
        ),
    ]
