# Generated by Django 3.2.17 on 2023-02-15 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0005_auto_20230207_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='bitrh_place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='db',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ecp.departments'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='fam',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='im',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='ot',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='pasp_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='pasp_dep',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='pasp_kem',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='pasp_n',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='pasp_s',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='post',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='snils',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
