# Generated by Django 3.2.17 on 2023-02-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0006_auto_20230215_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
