# Generated by Django 3.2.17 on 2023-02-17 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0007_persons_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecp',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='bitrh_place',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='persons',
            name='db',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='persons',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecp.departments'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='fam',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='persons',
            name='im',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='persons',
            name='pasp_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='persons',
            name='pasp_dep',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='persons',
            name='pasp_kem',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='persons',
            name='pasp_n',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='persons',
            name='pasp_s',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='persons',
            name='snils',
            field=models.CharField(max_length=14),
        ),
    ]
