# Generated by Django 3.2.17 on 2023-03-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0008_auto_20230217_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
