# Generated by Django 3.2.17 on 2023-03-09 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0009_persons_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('date', models.DateField(default=datetime.date(2023, 3, 9))),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='ecp',
            name='date',
        ),
        migrations.AddField(
            model_name='ecp',
            name='attorney_date',
            field=models.DateField(default=datetime.date(2023, 3, 9)),
        ),
        migrations.AddField(
            model_name='persons',
            name='decrees',
            field=models.ManyToManyField(to='ecp.Decrees'),
        ),
    ]
