# Generated by Django 3.2.17 on 2023-03-09 05:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0010_auto_20230309_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decrees',
            options={'verbose_name': 'Приказ', 'verbose_name_plural': 'Приказы'},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Отделение/Отдел', 'verbose_name_plural': 'Отделения/Отделы'},
        ),
        migrations.AlterModelOptions(
            name='ecp',
            options={'verbose_name': 'ЭЦП', 'verbose_name_plural': 'ЭЦПшки'},
        ),
        migrations.AlterModelOptions(
            name='persons',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RemoveField(
            model_name='ecp',
            name='attorney_date',
        ),
        migrations.AddField(
            model_name='ecp',
            name='date_get',
            field=models.DateField(null=True, verbose_name='Дата получения'),
        ),
        migrations.AddField(
            model_name='ecp',
            name='date_valid',
            field=models.DateField(null=True, verbose_name='Действует до'),
        ),
        migrations.AlterField(
            model_name='ecp',
            name='date_start',
            field=models.DateField(default=datetime.date(2023, 3, 9), verbose_name='Дата подачи заявки'),
        ),
        migrations.AlterField(
            model_name='ecp',
            name='key',
            field=models.CharField(max_length=100, null=True, verbose_name='Код ключа'),
        ),
        migrations.AlterField(
            model_name='ecp',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecp.persons', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='bitrh_place',
            field=models.CharField(max_length=50, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='db',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='decrees',
            field=models.ManyToManyField(to='ecp.Decrees', verbose_name='Приказы'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecp.departments', verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='fam',
            field=models.CharField(max_length=40, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='im',
            field=models.CharField(max_length=40, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен?'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='ot',
            field=models.CharField(max_length=40, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='pasp_date',
            field=models.DateField(verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='pasp_dep',
            field=models.CharField(max_length=10, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='pasp_kem',
            field=models.CharField(max_length=255, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='pasp_n',
            field=models.CharField(max_length=10, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='pasp_s',
            field=models.CharField(max_length=10, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='Телефон для связи'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='post',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='snils',
            field=models.CharField(max_length=14, verbose_name='СНИЛС'),
        ),
    ]
