# Generated by Django 3.2.17 on 2023-03-09 07:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0011_auto_20230309_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=datetime.datetime(2023, 3, 9, 7, 50, 50, 82523, tzinfo=utc), verbose_name='Дата подачи заявки')),
                ('date_get', models.DateField(blank=True, null=True, verbose_name='Дата получения')),
                ('date_valid', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код ключа')),
            ],
            options={
                'verbose_name': 'ЭЦП',
                'verbose_name_plural': 'ЭЦПшки',
            },
        ),
        migrations.AlterField(
            model_name='decrees',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 9, 7, 50, 50, 74449, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='persons',
            name='ot',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон для связи'),
        ),
        migrations.DeleteModel(
            name='ECP',
        ),
        migrations.AddField(
            model_name='esigns',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecp.persons', verbose_name='Сотрудник'),
        ),
    ]
