# Generated by Django 3.2.17 on 2023-04-03 01:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0013_auto_20230315_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decrees',
            name='Number',
            field=models.IntegerField(verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='decrees',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 4, 3, 1, 15, 2, 739408, tzinfo=utc), verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='decrees',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Файл договора'),
        ),
        migrations.AlterField(
            model_name='esigns',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 4, 3, 1, 15, 2, 753863, tzinfo=utc), verbose_name='Дата подачи заявки'),
        ),
    ]
