# Generated by Django 3.2.17 on 2023-04-03 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0015_auto_20230403_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decrees',
            old_name='Number',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='decrees',
            name='d_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 3, 1, 22, 51, 802685, tzinfo=utc), verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='esigns',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 4, 3, 1, 22, 51, 809790, tzinfo=utc), verbose_name='Дата подачи заявки'),
        ),
    ]
