# Generated by Django 3.2.17 on 2023-04-06 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0016_auto_20230403_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decrees',
            name='d_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 5, 33, 57, 719042, tzinfo=utc), verbose_name='Дата приказа'),
        ),
        migrations.AlterField(
            model_name='decrees',
            name='file',
            field=models.FileField(upload_to='static/uploads/', verbose_name='Файл приказа'),
        ),
        migrations.AlterField(
            model_name='decrees',
            name='number',
            field=models.IntegerField(verbose_name='Номер приказа'),
        ),
        migrations.AlterField(
            model_name='esigns',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 5, 33, 57, 726147, tzinfo=utc), verbose_name='Дата подачи заявки'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='decrees',
            field=models.ManyToManyField(blank=True, null=True, related_name='decrees', to='ecp.Decrees', verbose_name='Приказы'),
        ),
    ]
