# Generated by Django 4.2.1 on 2023-06-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0019_esigns_cert_esigns_request_link_esigns_request_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esigns',
            name='request_link',
        ),
        migrations.RemoveField(
            model_name='esigns',
            name='request_num',
        ),
    ]
