# Generated by Django 4.2.1 on 2023-06-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0022_auto_20230616_0944'),
    ]

    operations = [
    ]
