# Generated by Django 4.2.1 on 2023-06-16 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0024_auto_20230616_0946'),
    ]

    operations = [
    ]
