# Generated by Django 4.2.1 on 2023-06-16 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0025_auto_20230616_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esigns',
            name='request_link',
        ),
    ]
