# Generated by Django 4.2.1 on 2023-06-16 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0026_remove_esigns_request_link'),
    ]

    operations = [
    ]
