# Generated by Django 4.2.1 on 2023-06-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0027_auto_20230616_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='esigns',
            name='request_num',
            field=models.CharField(default='no', max_length=6, verbose_name='Номер запроса'),
            preserve_default=False,
        ),
    ]
