# Generated by Django 4.2.1 on 2023-06-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0028_esigns_request_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='esigns',
            name='request_link',
            field=models.CharField(default='no', max_length=255, verbose_name='Ссылка на черновик'),
            preserve_default=False,
        ),
    ]
