# Generated by Django 4.2.1 on 2023-06-19 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0029_esigns_request_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decrees',
            name='file',
            field=models.FileField(upload_to='uploads/decrees/%Y-%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл приказа'),
        ),
        migrations.AlterField(
            model_name='esigns',
            name='cert',
            field=models.FileField(blank=True, null=True, upload_to='uploads/certs/%Y-%m', validators=[django.core.validators.FileExtensionValidator(['pfx'])], verbose_name='Файл сертификата'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='decrees',
            field=models.ManyToManyField(related_name='persons', to='ecp.decrees', verbose_name='Приказы'),
        ),
    ]
