# Generated by Django 4.2.1 on 2023-06-26 01:35

import django.core.validators
from django.db import migrations, models
import ecp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0030_alter_decrees_file_alter_esigns_cert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decrees',
            name='file',
            field=models.FileField(upload_to=ecp.models.Decrees.get_translitfilename, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл приказа'),
        ),
        migrations.AlterField(
            model_name='esigns',
            name='cert',
            field=models.FileField(blank=True, null=True, upload_to=ecp.models.Esigns.get_translitfilename, validators=[django.core.validators.FileExtensionValidator(['pfx'])], verbose_name='Файл сертификата'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='decrees',
            field=models.ManyToManyField(blank=True, related_name='persons', to='ecp.decrees', verbose_name='Приказы'),
        ),
    ]
