# Generated by Django 4.2.1 on 2023-06-26 01:45

from django.db import migrations, models
import ecp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0031_alter_decrees_file_alter_esigns_cert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esigns',
            name='cert',
            field=models.FileField(blank=True, null=True, upload_to=ecp.models.Esigns.get_translitfilename, verbose_name='Файл сертификата'),
        ),
    ]
