# Generated by Django 4.2.1 on 2023-06-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0032_alter_esigns_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esigns',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Серийный номер сертификата'),
        ),
    ]
