# Generated by Django 4.2.1 on 2023-06-29 06:49

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import ecp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0033_alter_esigns_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='esigns',
            name='date_prompt',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приглашения на личный визит'),
        ),
        migrations.AddField(
            model_name='esigns',
            name='date_request',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачи заявления'),
        ),
        migrations.AddField(
            model_name='esigns',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='esigns',
            name='cert',
            field=models.FileField(blank=True, null=True, upload_to=ecp.models.Esigns.get_translitfilename, validators=[django.core.validators.FileExtensionValidator(['pfx'])], verbose_name='Файл сертификата'),
        ),
        migrations.AlterField(
            model_name='esigns',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания черновика'),
        ),
    ]
