# Generated by Django 4.2.1 on 2023-07-20 23:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ecp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0035_esigns_installed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='esigns',
            name='cert',
            field=models.FileField(blank=True, null=True, upload_to=ecp.models.Esigns.get_translitfilename, validators=[django.core.validators.FileExtensionValidator(['pfx', 'rar', 'reg'])], verbose_name='Файл сертификата'),
        ),
        migrations.AddField(
            model_name='departments',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ecp.departmenttypes', verbose_name='Тип подразделения'),
        ),
    ]
