# Generated by Django 4.2.1 on 2023-09-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0036_departmenttypes_alter_esigns_cert_departments_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmenttypes',
            options={'verbose_name': 'Тип подразделений', 'verbose_name_plural': 'Типы подразделений'},
        ),
        migrations.RemoveField(
            model_name='esigns',
            name='installed',
        ),
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
