# Generated by Django 4.2.1 on 2023-10-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0039_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='name',
            new_name='setting_name',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='value',
            new_name='setting_value',
        ),
        migrations.AddField(
            model_name='settings',
            name='setting_description',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание настройки'),
            preserve_default=False,
        ),
    ]
