# Generated by Django 4.2.1 on 2023-10-30 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0040_rename_name_settings_setting_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsignStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_txt', models.CharField(max_length=100, verbose_name='Статус ЭЦП')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('date', models.DateField(verbose_name='Дата установления статуса')),
                ('esign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecp.esigns', verbose_name='ЭЦП')),
            ],
            options={
                'verbose_name': 'Статус ЭЦП',
                'verbose_name_plural': 'Статусы ЭЦП',
            },
        ),
    ]
