# Generated by Django 4.2.1 on 2023-11-08 07:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import ecp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0042_alter_esignstatus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='esigns',
            name='cer',
            field=models.FileField(blank=True, null=True, validators=[django.core.validators.FileExtensionValidator(['cer'])], verbose_name='Сертификат CER'),
        ),
        migrations.AlterField(
            model_name='esignstatus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата установления статуса'),
        ),
        migrations.AlterUniqueTogether(
            name='esignstatus',
            unique_together={('esign', 'status_txt', 'reason', 'link')},
        ),
    ]
