# Generated by Django 4.2.1 on 2023-11-08 07:53

import django.core.validators
from django.db import migrations, models
import ecp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0043_esigns_cer_alter_esignstatus_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esigns',
            name='cer',
            field=models.FileField(blank=True, null=True, upload_to=ecp.models.Esigns.get_translitfilename, validators=[django.core.validators.FileExtensionValidator(['cer'])], verbose_name='Сертификат CER'),
        ),
    ]
