# Generated by Django 4.2.1 on 2023-11-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0044_alter_esigns_cer'),
    ]

    operations = [
        migrations.AddField(
            model_name='esignstatus',
            name='status_code',
            field=models.IntegerField(default=0, verbose_name='Код статуса'),
            preserve_default=False,
        ),
    ]
