# Generated by Django 4.2.1 on 2023-11-27 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0045_esignstatus_status_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esigns',
            name='date_prompt',
        ),
        migrations.RemoveField(
            model_name='esigns',
            name='date_request',
        ),
    ]
