# Generated by Django 4.2.1 on 2024-03-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0046_remove_esigns_date_prompt_remove_esigns_date_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='vasya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='decrees',
            options={'ordering': ['d_date', 'number'], 'verbose_name': 'Приказ', 'verbose_name_plural': 'Приказы'},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ['name'], 'verbose_name': 'Отделение/Отдел', 'verbose_name_plural': 'Отделения/Отделы'},
        ),
        migrations.AlterModelOptions(
            name='departmenttypes',
            options={'ordering': ['name'], 'verbose_name': 'Тип подразделений', 'verbose_name_plural': 'Типы подразделений'},
        ),
        migrations.AlterModelOptions(
            name='esigns',
            options={'ordering': ['date_start'], 'verbose_name': 'ЭЦП', 'verbose_name_plural': 'ЭЦПшки'},
        ),
        migrations.AlterModelOptions(
            name='persons',
            options={'ordering': ['fam', 'im', 'ot', 'db'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
