# Generated by Django 4.2.1 on 2024-03-06 23:03

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ecp', '0049_delete_customuserpermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserPermissions',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.permission')),
            ],
            options={
                'permissions': (('guest', "Can view only guest esign's data"), ('viewer', "Can view all esign's data"), ('manager', 'Can to do everything')),
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
