# Generated by Django 4.2.1 on 2024-04-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecp', '0051_delete_customuserpermissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vasya',
        ),
    ]
